### ISSUE TITLE
[1.20.1] Eden Cadillion weird agro teleport glitch 

### ISSUE THREAD

**Issue by Spookygalore** [DivineRPG/DivineRPG#656] opened 2024-06-24 21:46 UTC
When a Eden Cadillion agros onto me it does this odd wierd behavior where it looks around for a few seconds then teleports slightly, kind of annoying and unfair when dealing with these guys in 2-3 packs. Happens with all Eden’s I encounter in the Eden Dimension

Here’s video of it happening; https://drive.google.com/file/d/1QgqPJYoCJRdYIDtXKw3faenTluHwNCff/view?usp=drivesdk

**Comment by NicosaurusRex99** [comment] 2024-06-25 02:50
This is supposed to be a charging attack but the visuals dont seem to look right. Basically the issue is the cadillion doesnt seem to be looking where its charging and its legs dont animate at the same speed as it moves

**Comment by NicosaurusRex99** [comment] 2024-09-07 06:49
This should be fixed in 1700930

**Closed as completed by NicosaurusRex99** 2024-09-07 06:49 UTC
Labels: bug
