### ISSUE TITLE
Problem with Iceika

### ISSUE THREAD

**Issue by Finesha** [DivineRPG/DivineRPG#466] opened 2022-01-31 14:19 UTC
DivineRPG version 1.8.3

Describe the bug:

1- Underground dungeons are not bein' anyhow connected to the caves, or to be precise, I couldn't spot any caves even on spectator mode.

2- In those dungeons, there is also problem that destroyed spawners are dropping and player is able to pick 'em up.

3- All the dungeons are the same, single room formula with 1 spawner and 1 water block appearing instead of chest.

4- Santa set is having some issues, the one I noticed is no running boost but slowness instead

To reproduce:

I suggest to take a closer look at it while using spectator mode

Expected behavior

1- Appearence of both caves and dungeons within their area.

2-  Destruction of spawner, non dropable. 

3- More advanced dungeons including at least 1 or more spawners, along with it's respectable rooms and treasure chests.

4- I expect Santa set to give it's respective boosts in the Iceika world.

Screenshots:
![image](https://user-images.githubusercontent.com/98753919/151809848-dc86f6db-1ad4-469b-aa84-bb5364c3f579.png)

![image](https://user-images.githubusercontent.com/98753919/151809878-edb3fd79-4b1b-4607-8a9a-234d87f9c021.png)

![image](https://user-images.githubusercontent.com/98753919/151809902-89f25fea-3d1d-49e5-b3d7-3fa0f2f488f2.png)

![image](https://user-images.githubusercontent.com/98753919/151809929-2590495a-3595-4931-84f4-baff16dd4444.png)

![image](https://user-images.githubusercontent.com/98753919/151809960-4dd187af-ebbe-42e2-8b4c-d3e3f3c2c66b.png)

**Comment by NicosaurusRex99** [comment] 2022-02-01 03:41
1. Thats how its always been, not a bug but something to keep notes of.
2. Thank you will fix that asap
3. Fixed in fcbeb9b
4. Fixed in 30131a3

**Closed as completed** 2022-02-01 04:09 UTC
