### ISSUE TITLE
1.19.2 - Crash on Server Thread in Singleplayer

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DivineRPG/DivineRPG#521] opened 2022-11-01 09:28 UTC
**DivineRPG version**
Forge Version 43.1.47
DivineRPG-1.9.6

**Modpack version**
Just drop your mod in this one. https://www.curseforge.com/minecraft/modpacks/fiction-friction/files/4058025

**Describe the bug**
Dunno something with tameables.

**To reproduce**
I have no idea.

**Expected behavior**
No crashes is ideal.

**Additional context**

Crash Log
https://gist.github.com/P3rf3ctXZer0/accfefecdee9ee1c3221a381f36424a6

Latest Log
https://gist.github.com/P3rf3ctXZer0/0ce3195b2ab082ccfa1cb3e425d8df3a

I was messing with xnet network when it crashed. I right clicked an icon.

I don't have time to test but out of respect I have reported the crash. Good luck on the mod I hope you can figure it out.

**Comment by NicosaurusRex99** [comment] 2022-11-01 09:31
Thanks for the report. I know what the issue is, it will be fixed in the next release

**Comment by P3rf3ctXZer0** [comment] 2022-11-01 09:56
No problem I know worse then incomplete info is no info. I report any crashes I have but I personally won't be able to hyper test them. I know some info is always better than none though :)

**Comment by NicosaurusRex99** [comment] 2022-11-01 09:56
This is a very easy fix. Just a null checker should remedy it

**Comment by P3rf3ctXZer0** [comment] 2022-11-01 10:14
If you want me to put the mod through the ringer I am working on v24.0.0 of my pack will it be ready in less than an hour?

**Comment by NicosaurusRex99** [comment] 2022-11-01 10:18
My test modpack has just under 200 mods installed it just didnt have pokecube

**Comment by NicosaurusRex99** [comment] 2022-11-01 10:28
incase its urgent, heres the probable fix

[https://www.dropbox.com/s/fklj4b77rgxrooo/DivineRPG-1.9.6.1.jar?dl=0](url)

**Closed as completed** 2022-11-01 10:32 UTC
