### ISSUE TITLE
Whale Spawning Issue

### ISSUE THREAD

**Issue by PossesiveGamer** [DivineRPG/DivineRPG#410] opened 2020-11-24 01:41 UTC
I would like to report either an issue or a bug in the mod. 
I currently am playing Divine Rpg and I am having too many Whales Spawn that it literally makes the game unplayable.
I have tried SpawnTableTweaker and InControl to try and fix these spawn rates of these guys but to no avail. There is over 100 to 200 that spawn in one area and in caves with 1 block water sources that it literally makes my game unplayable.

Here is two pictures I managed to capture showing it after waiting like 2 minutes for the game to catch up from the whale spawns:
![2020-11-23_19 33 18](https://user-images.githubusercontent.com/9295473/100035392-aed50200-2dc3-11eb-82ce-50116c9d50ed.png)

![2020-11-23_19 33 00](https://user-images.githubusercontent.com/9295473/100035453-d4620b80-2dc3-11eb-8663-b94ba1cc2e97.png)

**Comment by NicosaurusRex99** [comment] 2020-12-25 04:45
A temporary fix is 
```
/kill @e[type=divinerpg:whale]
/kill @e[type=divinerpg:shark]
/kill @e[type=divinerpg:liopleurodon]
```

However this isnt an ideal end solution

**Comment by NicosaurusRex99** [comment] 2021-02-28 10:11
Since we are unable to modify 1.12.2 source anymore i am forced to close this issue.
However
A temporary fix is

```
/kill @e[type=divinerpg:whale]
/kill @e[type=divinerpg:shark]
/kill @e[type=divinerpg:liopleurodon]
```

However this isnt an ideal end solution

An alternative solution switch to peaceful then switch back

**Closed as completed by NicosaurusRex99** 2021-02-28 10:11 UTC
Labels: bug

**Comment by Nagapito** [comment] 2021-09-10 23:13
Not able to modify 1.12.2 is different of not wanting. The code is still there on github, it just finding the cause, fix it and make a new version!  
  
The solution you are proposting its idiotic to be simpatic!
Or you have this commands running every 2 seconds since its what it takes to spawn 2 thousand wales and constantly degrading the server or play in peaceful and have zero mobs in the game......

**Comment by NicosaurusRex99** [comment] 2021-09-11 02:57
Even if I wanted to I couldn't. Forge is no longer supporting 1.12.2 dev environments. Ive simply provided a work around and not a fix. There is nothing more i can/will do to fix this.

**Comment by WolfBV** [comment] 2022-01-25 22:26
Same with Rainbour ahhh >.< I'll just use the 1.16 version

**Comment by hueput** [comment] 2025-03-13 12:08
You didn't fix it. Why it is closed?

**Comment by Xplodin** [comment] 2025-09-22 11:42
> I would like to report either an issue or a bug in the mod. I currently am playing Divine Rpg and I am having too many Whales Spawn that it literally makes the game unplayable. I have tried SpawnTableTweaker and InControl to try and fix these spawn rates of these guys but to no avail. There is over 100 to 200 that spawn in one area and in caves with 1 block water sources that it literally makes my game unplayable.
> 
> Here is two pictures I managed to capture showing it after waiting like 2 minutes for the game to catch up from the whale spawns: ![2020-11-23_19 33 18](https://user-images.githubusercontent.com/9295473/100035392-aed50200-2dc3-11eb-82ce-50116c9d50ed.png)
> 
> ![2020-11-23_19 33 00](https://user-images.githubusercontent.com/9295473/100035453-d4620b80-2dc3-11eb-8663-b94ba1cc2e97.png)

Made a fix for this not too long ago.
https://www.curseforge.com/minecraft/mc-mods/drpgspawnfix

Feel free to use it in any way.
Sorry for necroposting, got fed up with this issue never being solved properly and took it to my own hands

**Comment by jtjjjj08** [comment] 2025-09-27 13:10
I'm having the same issue on the 1.7.10 version. Can a fix be done to that one to?

**Comment by NicosaurusRex99** [comment] 2025-09-27 16:26
1.7.10 isnt supported by the main devs anymore. charleadev did the latest 1.7.10 fixes alone. We just approved it. I suggest just using the drpgspawnfix mod that Xplodin linked above

**Comment by jtjjjj08** [comment] 2025-09-27 20:08
Last update for legacy was last updated in March. You did not just approve it> 1.7.10 isnt supported by the main devs anymore. charleadev did the latest 1.7.10 fixes alone. We just approved it. I suggest just using the drpgspawnfix mod that Xplodin linked above

**Comment by Xplodin** [comment] 2025-09-27 20:13
I can try making a 1.7.10 version. Ill also try adding those rainbow bat things to the config (cant remember name atm)

**Comment by jtjjjj08** [comment] 2025-09-27 20:18
That would be great thank you> I can try making a 1.7.10 version. Ill also try adding those rainbow bat things to the config (cant remember name atm)

**Comment by NicosaurusRex99** [comment] 2025-09-28 05:17
oh, i was under the impression this was 1.7.10. MB

**Comment by jtjjjj08** [comment] 2025-09-28 05:21
I'm talking about 1.7.10 the post was asking about 1.12.2 but the same issue happens on 1.7.10> oh, i was under the impression this was 1.7.10. MB
