### ISSUE TITLE
[1.20.1] Artifacts + DivineRPG duping items that are in artifact slots.

### ISSUE THREAD

**Issue by AXYEPO** [DivineRPG/DivineRPG#623] opened 2023-12-28 21:49 UTC
Playing on version 1.20.1 I found the problem of duping items that are in slots for artifacts when you enter the portal after defeating the dragon. Can this be fixed?

**Comment by AXYEPO** [comment] 2023-12-28 22:00
The latest version without this bug is "DivineRPG-1.10.6.1.jar". Everything above this version has this bug.

**Comment by TonimatasDEV** [comment] 2024-01-22 15:30
Same problem with 1.10.7.2

**Comment by NicosaurusRex99** [comment] 2024-01-22 15:31
i wouldnt have expected it to be fixed in 1.10.7.2. I will mark it fixed when the issue is fixed

**Comment by tixomirof** [comment] 2024-02-13 07:30
Same issue happens if you enable gamerule keepInventory true and die

**Comment by vjperez724** [comment] 2024-02-17 16:36
Just a warning to anyone using a backpack mod that goes in a curios slot.  Duplicating the backpack will delete all items in the backpack, at least with Sophisticated Backpacks.  I haven't tried other mods.

**Comment by Greenjiao** [comment] 2024-06-26 11:31
hope fixed，thanks contributor

**Comment by velocityraptor-real** [comment] 2024-07-18 07:29
should be fixed in latest version: DivineRPG 1.10.7.4.

**Closed as completed by velocityraptor-real** 2024-07-18 07:29 UTC
