### ISSUE TITLE
Eden Tomo suspected crashing the server

### ISSUE THREAD

**Issue by alphalee65** [DivineRPG/DivineRPG#565] opened 2023-04-22 15:43 UTC
I run a server with tons of mods and recently entered the Eden. Game crasshed all of a sudden and when i check the crash report it seems to be pointing to Eden Tomo being the issue. Am running the letest version for 1.19.2 (DivineRPG 1.9.6.8). Please do help as i have no idea whats really happening. Thank you.

[crash-2023-04-22_23.38.49-server.txt](https://github.com/DivineRPG/DivineRPG/files/11301686/crash-2023-04-22_23.38.49-server.txt)

**Comment by NicosaurusRex99** [comment] 2023-04-22 17:18
this happened witht he It Shall Not Tick mod but i cant see it in your logs, ensure its not installed

**Comment by alphalee65** [comment] 2023-04-22 18:08
> this happened witht he It Shall Not Tick mod but i cant see it in your logs, ensure its not installed

i dont recall having that mod as i manually installed every single mod myself. It doesnt seem to be.
The issue now is if i dont hit the Eden tomo its fine, tho i need someone else to log in so it doesnt crash the person who crashed the server's game

**Comment by NicosaurusRex99** [comment] 2023-04-22 18:32
- Hmm. Something else must be modifying ticks

**Comment by Edgeburn** [comment] 2023-04-23 02:21
I've also been having server crashes as a result of Eden Tomo ticking entities. We don't have the "It Shall Not Tick" mod nor do we have any mods that should be effecting ticks, this is a private custom mod pack. 

Here is our [server crash log](https://mclo.gs/2hUiXzE)

**Comment by Edgeburn** [comment] 2023-04-23 02:30
After further examination, the crash seems to happen when the mobs try to attack the player. Here is the same crash log https://mclo.gs/oWUgDlW

**Comment by NicosaurusRex99** [comment] 2023-04-23 03:14
again, it all points to 
`at divinerpg.entities.base.EntityPeacefulUntilAttacked.m_8119_(EntityPeacefulUntilAttacked.java:90) ~[DivineRPG-1.9.6.8.jar%23313!/:**.**.**.**]`
which is this [EntityPeacefulUntilAttacked:90](https://github.com/DivineRPG/DivineRPG/blob/1.19.2/src/main/java/divinerpg/entities/base/EntityPeacefulUntilAttacked.java#L90)
however that alone isnt enough to diagnose anything. i need to figure out what is breaking the tick method

**Comment by NicosaurusRex99** [comment] 2023-04-23 03:24
Mods i dont know what they are. incantare, pigpen, lovers_song, paragon and scena. Could you describe what each of these do or link me their mod page

notes* you have both spark and observable installed, is this intentional?

**Comment by Edgeburn** [comment] 2023-04-23 04:00
> Mods i dont know what they are. incantare, pigpen, lovers_song, paragon and scena. Could you describe what each of these do or link me their mod page

Incantare and lovers_song are private mods written by myself, neither of them touch entity ticking code in any way. 

Incantare is a WIP mod that adds new enchants to the game (currently only one). I have a [GitHub repo](https://github.com/edge217/Incantare) for it, although I don't think my mod should be the cause, as we've not had any other ticking entity crashes with the mod installed.

All of the other mods you mentioned are dependencies, with [PigPen](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher) being a dependency for Dark Utilities and Paragon (can't find the curseforge link) is a config library for something else in our modpack

Lovers_Song only adds a single music disc to the game, which has me and my gf's special song.

> 
> notes* you have both spark and observable installed, is this intentional?

Yes, this is intentional. I've not used Observable before this, but I've seen it installed alongside Spark in ATM8, so I assumed it wouldn't cause issues.

**Comment by NicosaurusRex99** [comment] 2023-04-23 04:03
hmm

**Comment by Cydaine** [comment] 2023-04-23 21:34
I'm having the same issue with also Wildwood Tomo, Eden Tomo and Epiphite. 
With and without Optifine, mind ya. I was suspecting it was that at first but seeing this thread, I do believe it is the mobs...


[crash-2023-04-23_16.28.50-server.txt](https://github.com/DivineRPG/DivineRPG/files/11305002/crash-2023-04-23_16.28.50-server.txt)
[crash-2023-04-23_16.49.36-server.txt](https://github.com/DivineRPG/DivineRPG/files/11305003/crash-2023-04-23_16.49.36-server.txt)
[crash-2023-04-23_17.17.33-server.txt](https://github.com/DivineRPG/DivineRPG/files/11305004/crash-2023-04-23_17.17.33-server.txt)
[crash-2023-04-22_23.38.49-server.txt](https://github.com/DivineRPG/DivineRPG/files/11305006/crash-2023-04-22_23.38.49-server.txt)

**Comment by Edgeburn** [comment] 2023-04-24 02:36
We've just had another crash from the Samek mob

https://mclo.gs/VEZ9gn0

**Comment by alphalee65** [comment] 2023-04-26 10:18
> 

can confirm this is also happening

**Comment by NicosaurusRex99** [comment] 2023-04-29 14:01
should be fixed in [a9bb2ad](https://github.com/DivineRPG/DivineRPG/commit/a9bb2adc67b64a3bb2b654dcb4dc6c92be7899d0), [5e9f72d](https://github.com/DivineRPG/DivineRPG/commit/5e9f72d550553e60f91d94eb86455d10c33b9f76) or [82bfae7](https://github.com/DivineRPG/DivineRPG/commit/82bfae7ff34afe508d68fc0650f85ca519ef96a0)

**Closed as completed by NicosaurusRex99** 2023-04-29 14:01 UTC
