### ISSUE TITLE
Problems in Divine RPG 1 16 5

### ISSUE THREAD

**Issue by amused92octopus** [DivineRPG/DivineRPG#473] opened 2022-03-12 18:37 UTC
Problems in Divine RPG 1 16 5 (translated into English) : 1 If you take a mystical clock in your left hand, you can endlessly call on an ancient entity (brown grasshopper). Also a problem with this and other bosses - they do not attack the player, they only hit if they approach, they get stuck and behave strangely. 2 The sun boss in the world of eden can only be summoned once, after which he cannot be summoned in any altars, but precious pieces of eden are spent. 3 do not spawn ores in the world of eden. 4 monsters from divine rpg don't appear in hell. 5. sea monsters are neutral to the player, only the blue crocodile attacks. 6 Poor textures (exceptions: textures and updated mob 3d models - they look amazing!). I redrawn several textures, I took others from minecraft and changed them in photoshop, I want to update the devine rpg mod in all plans, including the textures of blocks and objects (I can throw off some textures). 7 After hitting with a sword with the "conspiracy of fire" charm, some monsters disappear: a crab, a tomo of Edema (a green frog with antennae) King of Crabs. Unfortunately, due to the fact that the boss in Eden cannot be re-killed, the monsters in hell do not appear, and the ores of Eden are not generated, the mod is IMPOSSIBLE to pass. The previously listed errors and shortcomings also interfere with the passage. I hope for a bright future for the Divine rpg mod, because I remember the old versions of this mod, when there were no such serious problems.

**Comment by Locomenmod** [comment] 2022-03-13 13:52
Duplicate of #472

**Closed as completed by Locomenmod** 2022-03-13 13:52 UTC
Labels: duplicate
