### ISSUE TITLE
Server crash upon joining with Lady Luna

### ISSUE THREAD

**Issue by TheSerenin** [DivineRPG/DivineRPG#349] opened 2015-10-22 17:44 UTC
I'm managing a private server for my friends and I (5 in total) which has a private modpack installed created by me which has Divine RPG included.

As of today, as my friends were playing, I got messaged by my fiancé that the server crashed. To which I was faced with the following crash log:

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 22/10/15 10:56
Description: Ticking entity

java.lang.NoSuchMethodError: net.divinerpg.entities.vethea.EntityLadyLunaSparkler.func_70016_h(DDD)V
	at net.divinerpg.entities.vethea.EntityLadyLunaSparkler.<init>(EntityLadyLunaSparkler.java:29)
	at net.divinerpg.entities.vethea.EntityLadyLuna.func_70636_d(EntityLadyLuna.java:78)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.divinerpg.entities.vethea.EntityLadyLunaSparkler.<init>(EntityLadyLunaSparkler.java:29)
	at net.divinerpg.entities.vethea.EntityLadyLuna.func_70636_d(EntityLadyLuna.java:78)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: DRPGLadyLuna (net.divinerpg.entities.vethea.EntityLadyLuna)
	Entity ID: 316
	Entity Name: Lady Luna
	Entity's Exact location: 1.97, 70.00, 683.47
	Entity's Block location: World: (1,70,683), Chunk: (at 1,4,11 in 0,42; contains blocks 0,0,672 to 15,255,687), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: TheGreatTeaRPG_v1.0
	All players: 1 total; [EntityPlayerMP['JustCallMeDavid'/289, l='TheGreatTeaRPG_v1.0', x=-2.23, y=70.00, z=680.82]]
	Chunk stats: ServerChunkCache: 744 Drop: 0
	Level seed: 3023329086317235568
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-28,72,189), Chunk: (at 4,4,13 in -2,11; contains blocks -32,0,176 to -17,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8175370 game time, 8160163 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 33419 (now: false), thunder time: 1021 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.0-123.el7.x86_64
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1484449976 bytes (1415 MB) / 2189426688 bytes (2088 MB) up to 5578424320 bytes (5320 MB)
	JVM Flags: 10 total; -XX:+OptimizeStringConcat -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=minecraft -k -XX:OnError=curl https://api.creeper.host/callbacks/minecraft/crash.php?instance=minecraft -k -XX:-UseCompressedOops -Xmx6078M -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:ParallelGCThreads=2 -XX:+AggressiveHeap -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (server.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (server.jar) 
	UCHIJAAAA	backpacks16840{3.0.4} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.4.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
	UCHIJAAAA	divinerpg{1.4.1.1} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.1.jar) 
	UCHIJAAAA	aether{1.7.10-1.5.1} [Aether II] (aether-1.7.10-1.5.1.jar) 
	UCHIJAAAA	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCHIJAAAA	atum{0.6} [Atum] (Atum-1.7.10-0.6.77.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	CrossbowMod2{a0.1.6} [Crossbow Mod 2] (Crossbow-Mod-2-1.7-0.2.14.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) 
	UCHIJAAAA	stillhungry{1.7.2-2.1.0} [Still Hungry!] (stillhungry-1.7.2-2.1.1.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['REDACTED'/289, l='TheGreatTeaRPG_v1.0', x=-2.23, y=70.00, z=680.82]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

When I asked what they were doing before the crash, I was told they spawned Lady Luna.

I haven't been able to recreate the issue in single player.

**Comment by RadioactiveStud** [comment] 2015-10-22 17:49
Duplicate of #346 
Fixed in 1.4.1.2

**Closed by RadioactiveStud** 2015-10-22 17:49 UTC
Labels: duplicate
